Complete rules set to match GNAT check
AdaCore/langkit-query-language pull request #30
Opened 2021-01-26 14:05 UTC by leogermond

The full GNAT check set of rules is available at https://docs.adacore.com/live/wave/asis/html/gnatcheck_rm/gnatcheck_rm/predefined_rules.html

This set of commits aims to implement the exact equivalent in terms of rules into LKQL_checker

2021-01-26 14:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdaCore/langkit-query-language?pullRequest=30) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AdaCore/langkit-query-language?pullRequest=30) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdaCore/langkit-query-language?pullRequest=30) it.</sub>

2021-01-29 14:18 UTC, raph-amiard commented
Hello Léo!

Please add tests for each of those checks (take https://github.com/AdaCore/langkit-query-language/tree/master/testsuite/tests/checks/volatile_objects as an example, it should be pretty simple)

2021-02-05 10:03 UTC, raph-amiard requested changes
Another very important thing missing is tests (one per rule). Take inspiration from the existing checker tests, it should be pretty easy to figure out :)

2021-02-08 15:14 UTC, raph-amiard requested changes

2021-02-08 15:14 UTC, raph-amiard commented on lkql_checker/share/lkql/rules.json
>          "params": []
Missing test in this commit

2021-02-08 15:14 UTC, raph-amiard commented on lkql_checker/share/lkql/rules.json
>          "params": []
Again, missing test

2021-02-08 15:14 UTC, raph-amiard commented on lkql_checker/share/lkql/controlled_type_declarations.lkql
> +fun canonical_fully_qualified_name(t) =
Again, missing test

2021-02-09 12:23 UTC, raph-amiard submitted a review, later dismissed

2021-02-09 14:23 UTC, t-14 approved these changes

2021-02-12 11:25 UTC, raph-amiard approved these changes

2021-02-12 11:25 UTC, merged